# Yaml Parser:  http://yaml-online-parser.appspot.com/
init:
- 'decryptpasswords'
build:
- 'clean'
- 'checkout'
# - 'dw_dslint' Optional Now.  You must add the dslint package in the package.json 
# "dslint": "git+https://bitbucket.org/demandware/dslint.git",
- 'copy'
- 'sass:build'
- 'postcss:build'
- 'browserify:build'
- 'optimize'
- 'compress:code'
- 'compress:site_import'
upload:
- 'dw_upload:code'
- 'http:unzipUpload'
activate:
- 'http:login'
- 'http:welcomePage'
- 'http:activateCodeVersion'
dist:
- 'init'
- 'build'
- 'upload'
- 'activate'
- 'http:deleteUpload'
doc:
- 'init'
- 'jsdoc'
css:
- 'sass:dev'
- 'postcss:dev'
RunProjectBuild:
- 'init'
- 'build'
RunUploadCartridges:
- 'init'
- 'upload'
RunActivateBuild:
- 'init'
- 'activate'
GenerateJSDoc:
- 'doc'
default:
- 'init'
- 'css'
- 'browserify:watchDev'
- 'watch'
